# EVA/docker-compose.yml

services:
  eva-backend:
    container_name: eva-backend
    image: eva-backend:latest
    build:
      context: ./EVA_backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./EVA_backend:/app
      - ./EVA_backend/media:/app/media
      - ./EVA_backend/logfiles:/app/logfiles
      - ./EVA_backend/Second-Me/data/sqlite:/app/Second-Me/data/sqlite
      - F:/SecondMeData:/app/data
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - ./EVA_backend/.env
    environment:
      - PYTHONPATH=/app:/app/Second-Me
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - DOCKER_COMPOSE=true
      - PINECONE_API_KEY=5c190a0f-50bc-47c4-ad83-8eea0dd8185b
      - PINECONE_ENVIRONMENT=us-east-1-aws
      - PINECONE_MEMORY_INDEX_NAME=eva-memory
      - PINECONE_RULE_INDEX_NAME=eva-rule
      - PINECONE_TEXT_KEY=text
      - PINECONE_DIMENSION=1024
      - PINECONE_METRIC=cosine
      - PINECONE_CLOUD=aws
      - PINECONE_REGION=us-east-1
    networks:
      - eva-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health_check/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    platform: linux/amd64

  redis:
    container_name: eva-redis
    image: redis:6.2.6-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - eva-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    platform: linux/amd64

  db:
    container_name: eva-db
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eva_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - eva-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    platform: linux/amd64

  celery:
    container_name: eva-celery
    image: eva-backend:latest
    command: celery -A eva_backend_django worker -l info
    volumes:
      - ./EVA_backend:/app
      - ./EVA_backend/media:/app/media
      - ./EVA_backend/logfiles:/app/logfiles
    depends_on:
      - eva-backend
      - redis
      - db
    environment:
      - PYTHONPATH=/app:/app/Second-Me
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - DOCKER_COMPOSE=true
      - DJANGO_SETTINGS_MODULE=eva_backend_django.settings
      - TOKENIZERS_PARALLELISM=false
    env_file:
      - ./EVA_backend/.env
    healthcheck:
      test: ["CMD", "celery", "-A", "eva_backend_django", "inspect", "ping", "||", "exit", "1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 180s
    networks:
      - eva-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    platform: linux/amd64

  second-me-backend:
    build:
      context: ./EVA_backend/Second-Me
      dockerfile: Dockerfile.backend
    container_name: second-me-backend
    restart: unless-stopped
    ports:
      - "8002:8002"
      - "8080:8080"
    volumes:
      - F:/SecondMeData:/app/data
      - ./EVA_backend/Second-Me/logs:/app/logs
      - ./EVA_backend/Second-Me/run:/app/run
      - ./EVA_backend/Second-Me/resources:/app/resources
      - ./EVA_backend/Second-Me/docker:/app/docker
      - ./EVA_backend/Second-Me/.env:/app/.env
      - llama-cpp-build:/app/llama.cpp/build
    environment:
      - LOCAL_APP_PORT=8002
      - IN_DOCKER_ENV=1
      - PLATFORM=linux
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - eva-network

  second-me-frontend:
    build:
      context: ./EVA_backend/Second-Me
      dockerfile: Dockerfile.frontend
    container_name: second-me-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./EVA_backend/Second-Me/logs:/app/logs
      - ./EVA_backend/Second-Me/resources:/app/resources
    environment:
      - VITE_API_BASE_URL=http://second-me-backend:8002
    depends_on:
      - second-me-backend
    networks:
      - eva-network

networks:
  eva-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  llama-cpp-build:
    driver: local
